### ISSUE TITLE
Moodle - Paytm callback URL

### ISSUE THREAD

**Issue by sandipamukherjee** [Paytm-Payments/Paytm_Moodle_Kit#2]
Hi,
Which is the Call back URL for Moodle PAYTM enrolment plugin? 
I want to configure this plugin with moodle 3.3, when I have entered Paytm Merchant Website which is my staging website url it shows error. Can you please help regarding this?

Thanks,
Sandipa

**Comment by khatrianand** [comment]
I am also facing the same issue.   Was your issue resolved?  How did you solve it?

Thanks
Anand

**Comment by khatrianand** [comment]
Looks like... no one Paytm is paying attention....   the support looks VERY POOR.

I am dropping my plans to integrate with paytm.

Goodbye paytm

**Comment by Prabhat1Mishra** [comment]
Hi Everyone,

Sorry to delay replay.
You can use our updated plugin and if you are facing any issue then you raised your query on "integration.dev@paytm.com".

**Comment by khatrianand** [comment]
This is interesting….

You have replied the thread after two years !!
That too with a comment that “you can use the updated plugin”.

Do you even care to check, if the updated plugin was fixing the reported issue?   Infact, you have immediately closed the discussion thread.

I am running Moodle portal. And two years back I was in need of payment gateway integration. No one has a time to keep doing R&D and report errors on your product.  Two years back I tried integrating, but due to lack of support from PayTm, I have dropped my plans with paytm. The above thread is regarding same.

My straight simple question to PayTm team,  “ CAN I USE THE LATEST UPDATED PAYTM PLUGIN WITH MOODLE?”
This means:

  1.  You have already tested with latest Moodle version 3.8.1  -- can you confirm it?
  2.  Is your testbed ready with checking for this latest update?
  3.  The help document Is already updated with what config settings to be done while using it on testbed and what to be changed in production.

Kindly confirm all the above questions in simple yes/no answers.

Regards,
Anand Khatri
9764481681

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
